#!/bin/bash

set -o errexit

PKG='puppet7-release-bullseye.deb'

apt-get install -y curl
pushd /tmp >/dev/null
curl -O "https://apt.puppetlabs.com/${PKG}"
sudo dpkg -i "$PKG"
sudo apt-get update
apt-get install --no-install-recommends -y puppet-agent puppet-lint
popd >/dev/null
